//
//  EmailVerifyPresenter.swift
//  Basis-Auth-Demo
//
//  Created by rishabh on 05/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EmailVerifyPresentationLogic
{
    func presentInputEmail(response: EmailVerify.GetEmail.Response)
    func presentVerifyActionResponse(response: EmailVerify.VerifyAction.Response)
}

class EmailVerifyPresenter: EmailVerifyPresentationLogic
{
    weak var viewController: EmailVerifyDisplayLogic?
    
    // MARK: Do something
    
    func presentInputEmail(response: EmailVerify.GetEmail.Response)
    {
        let viewModel = EmailVerify.GetEmail.ViewModel(strEmail: response.email)
        viewController?.displayInputEmail(viewModel: viewModel)
    }
    
    func presentVerifyActionResponse(response: EmailVerify.VerifyAction.Response) {
        if response.success {
            let viewModel = EmailVerify.VerifyAction.ViewModel(success: response.success)
            viewController?.prepareRouterForDashboardTransition(viewModel: viewModel)
        }
        else {
            viewController?.displayVerifyActionFailed()
        }
    }
}
