//
//  EmailVerifyWorker.swift
//  Basis-Auth-Demo
//
//  Created by rishabh on 05/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class EmailVerifyWorker
{
    var requestManager = RequestManager()
    typealias VerifyActionAPIModel = EmailVerify.VerifyActionAPI.VerifyActionAPIModel
    
    func sendVerifyRequestToServer(jsonData: String, onCompletion: @escaping (_ apiResponse: VerifyActionAPIModel?, _ success: Bool) -> Void)
    {
        let verifyUrl = Globals.API_ENDPOINTS.verify
        requestManager.sendAsyncRequestWith(endpointUrl: verifyUrl, httpMethod: "PUT", jsonData: jsonData) { apiData, success in
            if (!success) {
                onCompletion(nil, success)
                return
            }
            
            guard let apiData = apiData else {
                onCompletion(nil, success)
                return
            }
            
            do {
                let apiResponseParsed = try JSONDecoder().decode(VerifyActionAPIModel.self, from: apiData)
                onCompletion(apiResponseParsed, success)
            }
            catch {
                onCompletion(nil, success)
                return
            }
        }
    }
}
