//
//  EmailLandingRouter.swift
//  Basis-Auth-Demo
//
//  Created by rishabh on 04/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EmailLandingRoutingLogic
{
    func routeToVerifyScene()
}

protocol EmailLandingDataPassing
{
    var dataStore: EmailLandingDataStore? { get }
}

class EmailLandingRouter: NSObject, EmailLandingRoutingLogic, EmailLandingDataPassing
{
    weak var viewController: EmailLandingViewController?
    var dataStore: EmailLandingDataStore?
    
    // MARK: Routing
    func routeToVerifyScene()
    {
        print("\nRouting...\n")
        let mainStoryboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = mainStoryboard.instantiateViewController(withIdentifier: "EmailVerifyViewController") as! EmailVerifyViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToVerifyScene(source: dataStore!, destination: &destinationDS)
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
    
    // MARK: Passing data
    func passDataToVerifyScene(source: EmailLandingDataStore, destination: inout EmailVerifyDataStore)
    {
        destination.isLogin = source.isLogin
        destination.token = source.token
        destination.email = source.email
    }
}
