//
//  EmailLandingModels.swift
//  Basis-Auth-Demo
//
//  Created by rishabh on 04/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EmailLanding
{
    // MARK: Use cases
    
    enum LoginAction
    {
        struct LoginRequest
        {
            var email: String
        }
        struct LoginResponse
        {
            var success: Bool
            var token: Int?
            var isLogin: Bool
        }
        struct LoginViewModel
        {
            var apiSuccess: Bool
        }
    }
    
    enum LoginActionAPI {
        // MARK: - Welcome
        struct LoginActionAPIModel: Codable {
            let success: Bool?
            let version: Version?
            let statusCode: Int?
            let responseCode, message: String?
            let results: Results?
        }

        // MARK: - Results
        struct Results: Codable {
            let wrongEmailTokenCount, resendEmailTokenCount, token: Int?
            let isLogin: Bool?
        }

        // MARK: - Version
        struct Version: Codable {
            let minimum, current: Int?
        }
    }
    
    enum PostLoginAction {
        struct NextStepRequest {
            var isLogin: Bool
            var token: Int
        }
        struct ViewModel {
            var isLogin: Bool
            var token: Int
            var email: String
        }
    }
}
