//
//  EmailLandingPresenter.swift
//  Basis-Auth-Demo
//
//  Created by rishabh on 04/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EmailLandingPresentationLogic
{
    func presentLoginResponse(response: EmailLanding.LoginAction.LoginResponse)
    func prepareForRouteVerify(isLogin: Bool, token: Int, email: String)
}

class EmailLandingPresenter: EmailLandingPresentationLogic
{
    
    weak var viewController: EmailLandingDisplayLogic?
    
    // MARK: Implementations
    
    func presentLoginResponse(response: EmailLanding.LoginAction.LoginResponse)
    {
        let viewModel = EmailLanding.LoginAction.LoginViewModel(apiSuccess: response.success)
        viewController?.loginActionComplete(viewModel: viewModel)
    }
    
    func prepareForRouteVerify(isLogin: Bool, token: Int, email: String) {
        let viewModel = EmailLanding.PostLoginAction.ViewModel(isLogin: isLogin, token: token, email: email)
        viewController?.callRouterForVerifyTransition(viewModel: viewModel)
    }
    
}
