//
//  EmailLandingWorker.swift
//  Basis-Auth-Demo
//
//  Created by rishabh on 04/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class EmailLandingWorker
{
    var requestManager = RequestManager()
    typealias LoginActionAPIModel = EmailLanding.LoginActionAPI.LoginActionAPIModel
    func sendLoginRequestToServer(jsonData: String, onCompletion: @escaping (_ apiResponse: LoginActionAPIModel?, _ success: Bool) -> Void)
    {
        let loginUrl = Globals.API_ENDPOINTS.login
        requestManager.sendAsyncRequestWith(endpointUrl: loginUrl, httpMethod: "POST", jsonData: jsonData) { apiData, success in
            if (!success) {
                onCompletion(nil, success)
                return
            }
            
            guard let apiData = apiData else {
                onCompletion(nil, success)
                return
            }
            
            do {
                let apiResponseParsed = try JSONDecoder().decode(LoginActionAPIModel.self, from: apiData)
                onCompletion(apiResponseParsed, success)
            }
            catch {
                onCompletion(nil, success)
                return
            }
        }
    }
}
