//
//  EmailLandingInteractor.swift
//  Basis-Auth-Demo
//
//  Created by rishabh on 04/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EmailLandingBusinessLogic
{
    func loginUsing(request: EmailLanding.LoginAction.LoginRequest)
}

protocol EmailLandingDataStore
{
    var email: String { get set }
}

class EmailLandingInteractor: EmailLandingDataStore
{
    var presenter: EmailLandingPresentationLogic?
    var worker: EmailLandingWorker?
    var email: String = ""
    
    func callApi(request: EmailLanding.LoginAction.LoginRequest, jsonData: String)
    {
        worker = EmailLandingWorker()
        worker?.sendLoginRequestToServer(jsonData: jsonData, onCompletion: { [unowned self] apiResponse, success in
            let tokenReceived = apiResponse?.results?.token ?? 0
            let isLogin = apiResponse?.results?.isLogin ?? false
            
            let response = EmailLanding.LoginAction.LoginResponse(success: success, token: tokenReceived, isLogin: isLogin)
            self.presenter?.presentSomething(response: response)
        })
    }
}

extension EmailLandingInteractor: EmailLandingBusinessLogic {
    func loginUsing(request: EmailLanding.LoginAction.LoginRequest) {
        let jsonData = "{\"email\":\"\(request.email)\"}"
        
        callApi(request: request, jsonData: jsonData)
    }
}
