//
//  EmailLandingInteractor.swift
//  Basis-Auth-Demo
//
//  Created by rishabh on 04/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EmailLandingBusinessLogic
{
    func loginUsing(request: EmailLanding.LoginAction.LoginRequest)
    func routeToVerifyScene()
}

protocol EmailLandingDataStore
{
    var isLogin: Bool? { get set }
    var token: Int? { get set }
    var email: String? { get set }
}

class EmailLandingInteractor: EmailLandingDataStore
{
    var isLogin: Bool?
    var token: Int?
    var email: String?
    
    var presenter: EmailLandingPresentationLogic?
    var worker: EmailLandingWorker?
    
    func callApi(request: EmailLanding.LoginAction.LoginRequest, jsonData: String)
    {
        email = request.email
        worker = EmailLandingWorker()
        worker?.sendLoginRequestToServer(jsonData: jsonData, onCompletion: { [unowned self] apiResponse, success in
            self.token = apiResponse?.results?.token ?? 0
            self.isLogin = apiResponse?.results?.isLogin ?? false
            
            let response = EmailLanding.LoginAction.LoginResponse(success: success, token: self.token ?? 0, isLogin: self.isLogin ?? false)
            self.presenter?.presentLoginResponse(response: response)
        })
    }
    
    func forwardPostLoginToPresenter(request: EmailLanding.PostLoginAction.NextStepRequest) {
        self.presenter?.prepareForRouteVerify(isLogin: self.isLogin ?? false, token: self.token ?? 0, email: self.email ?? "")
    }
}

extension EmailLandingInteractor: EmailLandingBusinessLogic {
    func routeToVerifyScene() {
        let request: EmailLanding.PostLoginAction.NextStepRequest = .init(isLogin: self.isLogin ?? false, token: self.token ?? 0)
        forwardPostLoginToPresenter(request: request)
    }
    
    func loginUsing(request: EmailLanding.LoginAction.LoginRequest) {
        let jsonData = "{\"email\":\"\(request.email)\"}"
        
        callApi(request: request, jsonData: jsonData)
    }
}
