//
//  EmailDashboardInteractor.swift
//  Basis-Auth-Demo
//
//  Created by rishabh on 05/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EmailDashboardBusinessLogic
{
    func doSomething(request: EmailDashboard.Something.Request)
}

protocol EmailDashboardDataStore
{
    var isLogin: Bool? { get set }
    var email: String? { get set }
    var verificationCode: String? { get set }
    var verificationIsLogin: Bool? { get set }
}

class EmailDashboardInteractor: EmailDashboardBusinessLogic, EmailDashboardDataStore
{
    var isLogin: Bool?
    var token: Int?
    var email: String?
    var verificationCode: String?
    var verificationIsLogin: Bool?
    
    var presenter: EmailDashboardPresentationLogic?
    var worker: EmailDashboardWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: EmailDashboard.Something.Request)
    {
        worker = EmailDashboardWorker()
        worker?.doSomeWork()
        
        let response = EmailDashboard.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
