//
//  EmailDashboardRouter.swift
//  Basis-Auth-Demo
//
//  Created by rishabh on 05/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EmailDashboardRoutingLogic
{
    func routeToEmailLandingScene()
}

protocol EmailDashboardDataPassing
{
    var dataStore: EmailDashboardDataStore? { get }
}

class EmailDashboardRouter: NSObject, EmailDashboardRoutingLogic, EmailDashboardDataPassing
{
    weak var viewController: EmailDashboardViewController?
    var dataStore: EmailDashboardDataStore?
    
    // MARK: Routing
    func routeToEmailLandingScene() {
        print("\nRouting Backward...\n")
        if let landingVC = viewController?.navigationController?.viewControllers.first {
            viewController?.navigationController?.popToViewController(landingVC, animated: true)
        }
    }
}
