//
//  EmailDashboardInteractor.swift
//  Basis-Auth-Demo
//
//  Created by rishabh on 05/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EmailDashboardBusinessLogic
{
    func showUserInfo(request: EmailDashboard.UserInformation.Request)
    func requestRertyLogin()
}

protocol EmailDashboardDataStore
{
    var isLogin: Bool? { get set }
    var email: String? { get set }
    var verificationCode: Int? { get set }
    var verificationIsLogin: Bool? { get set }
    var message: String { get set }
    var userName: String? { get set }
    var success: Bool { get set }
}

class EmailDashboardInteractor: EmailDashboardBusinessLogic, EmailDashboardDataStore
{
    var success: Bool = false
    var message: String = ""
    var userName: String?
    var isLogin: Bool?
    var email: String?
    var verificationCode: Int?
    var verificationIsLogin: Bool?
    
    var presenter: EmailDashboardPresentationLogic?
    var worker: EmailDashboardWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func showUserInfo(request: EmailDashboard.UserInformation.Request)
    {
        let response = EmailDashboard.UserInformation.Response(isLogin: isLogin ?? false,
                                                               verificationIsLogin: verificationIsLogin ?? false,
                                                               email: email ?? "",
                                                               code: verificationCode ?? 0,
                                                               responseMessage: message,
                                                               apiSuccess: success,
                                                               userFullName: userName)
        presenter?.displayUserInfo(response: response)
    }
    
    func requestRertyLogin() {
        presenter?.prepareRouterForRetryLogin()
    }
}
