//
//  EmailDashboardPresenter.swift
//  Basis-Auth-Demo
//
//  Created by rishabh on 05/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EmailDashboardPresentationLogic
{
    func displayUserInfo(response: EmailDashboard.UserInformation.Response)
    func prepareRouterForRetryLogin()
}

class EmailDashboardPresenter: EmailDashboardPresentationLogic
{
    weak var viewController: EmailDashboardDisplayLogic?
    
    // MARK: Do something
    
    func displayUserInfo(response: EmailDashboard.UserInformation.Response)
    {
        let viewModel = EmailDashboard.UserInformation.ViewModel(isLogin: response.isLogin, email: response.email, code: response.code, responseMessage: response.responseMessage, userFullName: response.userFullName)
        if !response.verificationIsLogin {
            if response.apiSuccess {
                viewController?.displayPopupWithSignupInfo(viewModel: viewModel)
            }
            else {
                viewController?.displayPopupWithErrorInfo(viewModel: viewModel)
            }
        }
        else {
            viewController?.displayUserInfo(viewModel: viewModel)
        }
    }
    
    func prepareRouterForRetryLogin() {
        viewController?.prepareRouterToRetryLogin()
    }
}
