//
//  EmailDashboardModels.swift
//  Basis-Auth-Demo
//
//  Created by rishabh on 05/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EmailDashboard
{
  // MARK: Use cases
  
  enum UserInformation
  {
    struct Request
    {
        
    }
    struct Response
    {
        var isLogin: Bool
        var verificationIsLogin: Bool
        var email: String
        var code: Int
        var responseMessage: String
        var apiSuccess: Bool
        var userFullName: String?
    }
    struct ViewModel
    {
        var isLogin: Bool
        var email: String
        var code: Int
        var responseMessage: String
        
        var userFullName: String?
    }
  }
}
