//
//  EmailDashboardPresenter.swift
//  Basis-Auth-Demo
//
//  Created by rishabh on 05/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EmailDashboardPresentationLogic
{
  func presentSomething(response: EmailDashboard.Something.Response)
}

class EmailDashboardPresenter: EmailDashboardPresentationLogic
{
  weak var viewController: EmailDashboardDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: EmailDashboard.Something.Response)
  {
    let viewModel = EmailDashboard.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
